### ISSUE TITLE
Fishery.name bug in CompareBaseRecoveries.r

### ISSUE THREAD

**Issue by catarinawor** [PSC-CTC/PSC-CAS-R#1]
Hey Nick,

I seems that there might be a bug in the updated version of your script. 
We get error when running lines 146-158 (to produce the fishery.modifed.df). The variables FisheryName.x and FisheryName.y seem to be missing from the compare.df. 

Do you think you could look at it? let us know and thanks again!!

**Comment by nick-komick** [comment]
fixed with lastest version, there was a few bugs that caused the issue.  

sorry about that, i should have caught it before committing.  Next time i will test outside of R Studio, because it can be hard to see the errors when the whole script runs.

Rock on :metal:
